### ISSUE TITLE
blackeye:error 404

### ISSUE THREAD

**Issue by DidIGitYou** [thelinuxchoice/blackeye#63]
i did not have any problems with getting the ip address...but when i enter the ip address on the browser,it says "error 404;not found" "the requested resource /login.html was not found on this server".please help me

**Comment by DidIGitYou** [comment]
nevermind,i fixed it.

**Comment by FireTroller** [comment]
How did you fix it?

**Comment by DidIGitYou** [comment]
It was my antivirus, it removed those html pages.

**Comment by DidIGitYou** [comment]
It was my antivirus, it removed those html pages.
